apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mlservice-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: mlservice
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 10
  pollingInterval: 5
  triggers:
  - type: rabbitmq
    metadata:
      host: "amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672/"
      queueName: tasks
      queueLength: "5"
