apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
  labels:
    app: victoria-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoria-metrics
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      containers:
      - name: victoria-metrics
        image: victoriametrics/victoria-metrics-single-node:latest
        args:
          - "--retentionPeriod=1"
        ports:
          - containerPort: 8428
---
apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
spec:
  selector:
    app: victoria-metrics
  ports:
    - protocol: TCP
      port: 8428
      targetPort: 8428
  type: ClusterIP
